flags: {}

packages:
- ./liquid-fixpoint
- '.'

extra-deps:
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
- intern-0.9.1.4
- located-base-0.1.0.0
- plugins-1.5.5.0
- floatshow-0.2.4
- aeson-0.11.1.4

compiler-check: newer-minor

resolver: lts-5.3
