flags: {}

packages:
- '.'
- location:
    git:    https://github.com/ucsd-progsys/liquid-fixpoint.git
    commit: 6d6bd34c9bcf8e1c1ff40514f2bc12b4fb4fd3df

extra-deps:
- plugins-1.5.5.0
- located-base-0.1.0.0
- ascii-progress-0.3.2.0
- concurrent-output-1.7.3
- intern-0.9.1.4
- haskell-src-exts-1.17.1
- dotgen-0.4.2
- fgl-visualize-0.1.0.1

resolver: lts-3.8
